// Mock data, form schemas, i18n strings for TTMFlow.
// Arrays are mutable so admin actions (publish form, start flow) can append in-memory.

export const i18n = {
  th: {
    appName: "TTMFlow",
    appSub: "ระบบจัดการคำขอภายในองค์กร",
    company: "บริษัท ทอล์คทูมี จำกัด",

    nav: {
      dashboard: "แดชบอร์ด",
      flows: "ขั้นตอนงาน (Flows)",
      newRequest: "สร้างคำขอใหม่",
      myRequests: "คำขอของฉัน",
      approvals: "รออนุมัติ",
      itQueue: "งานที่ได้รับมอบหมาย",
      archive: "คลังเอกสาร",
      notifications: "บันทึกการแจ้งเตือน",
      caseSummary: "Service Ticket Summary",
      settings: "ตั้งค่าฟอร์ม",
      integrations: "เชื่อมต่อการแจ้งเตือน",
      users: "จัดการผู้ใช้งาน",
      help: "ช่วยเหลือ",
    },

    role: {
      requester: "พนักงาน (Requester)",
      approver: "ผู้อนุมัติ (Approver)",
      it: "ทีมไอที (IT Staff)",
      admin: "ผู้ดูแลระบบ (Admin / QMR)",
      auditor: "ผู้ตรวจสอบ (Auditor)",
    },

    status: {
      draft: "ฉบับร่าง",
      pending: "รออนุมัติ",
      approved: "อนุมัติแล้ว",
      rejected: "ไม่อนุมัติ",
      inProgress: "กำลังดำเนินการ",
      done: "เสร็จสิ้น",
      cancelled: "ยกเลิก",
    },

    common: {
      search: "ค้นหา...",
      filter: "กรอง",
      all: "ทั้งหมด",
      submit: "บันทึก & ส่งคำขอ",
      saveDraft: "บันทึกฉบับร่าง",
      cancel: "ยกเลิก",
      next: "ถัดไป",
      back: "ย้อนกลับ",
      approve: "อนุมัติ",
      reject: "ไม่อนุมัติ",
      sign: "ลงลายเซ็น",
      preview: "ดูตัวอย่าง PDF",
      download: "ดาวน์โหลด PDF",
      view: "ดู",
      edit: "แก้ไข",
      send: "ส่ง",
      from: "จาก",
      to: "ถึง",
      date: "วันที่",
      time: "เวลา",
      requester: "ผู้แจ้ง",
      approver: "ผู้อนุมัติ",
      department: "แผนก",
      docNo: "เลขที่เอกสาร",
      type: "ประเภท",
      created: "สร้างเมื่อ",
      updated: "อัพเดตเมื่อ",
      step: "ขั้นที่",
      of: "จาก",
      open: "เปิดดู",
      newest: "ล่าสุดก่อน",
      oldest: "เก่าสุดก่อน",
      runningNumber: "เลขรันอัตโนมัติ",
      attach: "แนบไฟล์",
      detail: "รายละเอียด",
      noResults: "ไม่มีรายการ",
    },

    dash: {
      hello: "สวัสดี",
      welcome: "ภาพรวมคำขอและสถานะของทีม",
      myDraft: "ฉบับร่างของฉัน",
      awaitMe: "รอฉันอนุมัติ",
      inMyQueue: "งานในคิวของฉัน",
      thisMonth: "คำขอเดือนนี้",
      throughput: "ระยะเวลาดำเนินการเฉลี่ย",
      compliance: "ความครบถ้วน ISO",
      recent: "กิจกรรมล่าสุด",
      quickStart: "เริ่มอย่างรวดเร็ว",
      seeAll: "ดูทั้งหมด",
      byType: "คำขอตามประเภทฟอร์ม (30 วัน)",
      hours: "ชั่วโมง",
      days: "วัน",
    },

    forms: {
      title: "เลือกแบบฟอร์มที่ต้องการ",
      sub: "ทุกแบบฟอร์มได้รับการขึ้นทะเบียนตามมาตรฐาน ISO 9001 พร้อมเลขเอกสารอัตโนมัติ",
      categoryIT: "ฝ่ายเทคโนโลยีสารสนเทศ (IT)",
      categoryHR: "ฝ่ายทรัพยากรบุคคล (HR)",
      categoryFI: "ฝ่ายการเงิน (Finance)",
    },
  },
  en: {
    appName: "TTMFlow",
    appSub: "Internal Request Management",
    company: "Talk to Me Co., Ltd.",

    nav: {
      dashboard: "Dashboard",
      flows: "Flows",
      newRequest: "New Request",
      myRequests: "My Requests",
      approvals: "Awaiting Approval",
      itQueue: "Assigned Work",
      archive: "Document Archive",
      notifications: "Notification Log",
      caseSummary: "Service Ticket Summary",
      settings: "Form Templates",
      integrations: "Notification Integrations",
      users: "User Management",
      help: "Help",
    },

    role: {
      requester: "Employee (Requester)",
      approver: "Approver",
      it: "IT Staff",
      admin: "Admin / QMR",
      auditor: "Auditor",
    },

    status: {
      draft: "Draft",
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      inProgress: "In Progress",
      done: "Done",
      cancelled: "Cancelled",
    },

    common: {
      search: "Search...",
      filter: "Filter",
      all: "All",
      submit: "Save & Submit",
      saveDraft: "Save Draft",
      cancel: "Cancel",
      next: "Next",
      back: "Back",
      approve: "Approve",
      reject: "Reject",
      sign: "Sign",
      preview: "Preview PDF",
      download: "Download PDF",
      view: "View",
      edit: "Edit",
      send: "Send",
      from: "From",
      to: "To",
      date: "Date",
      time: "Time",
      requester: "Requester",
      approver: "Approver",
      department: "Department",
      docNo: "Doc No.",
      type: "Type",
      created: "Created",
      updated: "Updated",
      step: "Step",
      of: "of",
      open: "Open",
      newest: "Newest",
      oldest: "Oldest",
      runningNumber: "Auto running number",
      attach: "Attach file",
      detail: "Details",
      noResults: "No results",
    },

    dash: {
      hello: "Hello",
      welcome: "Overview of requests and team status",
      myDraft: "My drafts",
      awaitMe: "Awaiting my approval",
      inMyQueue: "Tasks in my queue",
      thisMonth: "Requests this month",
      throughput: "Average processing time",
      compliance: "ISO completeness",
      recent: "Recent activity",
      quickStart: "Quick start",
      seeAll: "See all",
      byType: "Requests by form type (30 days)",
      hours: "hours",
      days: "days",
    },

    forms: {
      title: "Choose a form to fill",
      sub: "All forms are registered under ISO 9001 with auto-generated document numbers",
      categoryIT: "Information Technology (IT)",
      categoryHR: "Human Resources (HR)",
      categoryFI: "Finance",
    },
  },
};

export const FORM_TEMPLATES = [
  {
    code: "FM-IT-01-01",
    icon: "monitor",
    color: "blue",
    category: "IT",
    titleTh: "ขอใช้ระบบ / อุปกรณ์",
    titleEn: "Request to Use System / Equipment",
    descTh: "ขอ Email, สิทธิ์ระบบ, PC, Notebook, Headset, VPN, License",
    descEn: "Request email, system access, PC, notebook, headset, VPN, license",
    approvers: ["หัวหน้าฝ่ายผู้แจ้ง", "ผู้จัดการฝ่าย IT", "เจ้าหน้าที่ IT ผู้รับงาน"],
    avgDays: 1.5,
  },
  {
    code: "FM-IT-01-09",
    icon: "phone",
    color: "violet",
    category: "IT",
    titleTh: "จัดการคิวรับสายระบบโทรศัพท์",
    titleEn: "PBX Queue Management",
    descTh: "สร้าง/ยกเลิกคิว, ปรับ Ring Strategy, เพิ่ม/ลด/โอนย้าย Agent",
    descEn: "Create/delete queue, ring strategy, add/remove/transfer agents",
    approvers: ["หัวหน้าโปรเจกต์", "ผู้จัดการฝ่าย IT", "เจ้าหน้าที่ IT"],
    avgDays: 0.8,
  },
  {
    code: "FM-IT-01-10",
    icon: "wrench",
    color: "amber",
    category: "IT",
    titleTh: "ขอจัดการติดตั้งอุปกรณ์ไอที",
    titleEn: "IT Equipment Installation",
    descTh: "เพิ่ม/ย้าย/ยกเลิกจุดติดตั้ง PC, IP Phone, SIM Gateway",
    descEn: "Add/move/decommission stations, IP phone, SIM gateway",
    approvers: ["หัวหน้าโปรเจกต์", "ผู้จัดการฝ่าย IT", "เจ้าหน้าที่ IT"],
    avgDays: 2.0,
  },
  {
    code: "FM-IT-01-11",
    icon: "lifebuoy",
    color: "rose",
    category: "IT",
    titleTh: "แจ้งซ่อมและขอความช่วยเหลือทางไอที",
    titleEn: "IT Support & Repair Ticket",
    descTh: "แจ้งอุปกรณ์เสีย, ลืมรหัสผ่าน, ขัดข้องเครือข่าย, VPN",
    descEn: "Report broken equipment, password reset, network, VPN",
    approvers: ["เจ้าหน้าที่ IT"],
    avgDays: 0.3,
  },
  {
    code: "FM-SL-04-01",
    icon: "trending-up",
    color: "blue",
    category: "SL",
    titleTh: "ใบแจ้งเปิดโครงการใหม่",
    titleEn: "New Project Kickoff",
    descTh: "ใช้โดยฝ่ายขายเพื่อแจ้งเปิดโครงการใหม่ สามารถผูกเข้ากับ Flow ข้ามแผนกได้",
    descEn: "Sales-led form for opening a new project; can be attached to a multi-dept Flow",
    approvers: ["Sales Manager", "Operations Director", "CEO Office"],
    avgDays: 2.0,
    sections: [
      {
        id: "sl_sec1", titleTh: "ข้อมูลโครงการ", titleEn: "Project info",
        fields: [
          { id: "projectName", type: "text", labelTh: "ชื่อโครงการ", labelEn: "Project name", required: true, span: 2 },
          { id: "client", type: "text", labelTh: "ลูกค้า", labelEn: "Client", required: true, span: 1 },
          { id: "seatCount", type: "number", labelTh: "จำนวน Seat ที่ต้องการ", labelEn: "Required seats", required: true, span: 1 },
          { id: "goLive", type: "date", labelTh: "วันที่เปิดให้บริการ (Go-live)", labelEn: "Go-live date", required: true, span: 1 },
          { id: "duration", type: "select", labelTh: "ระยะเวลาสัญญา", labelEn: "Contract duration", span: 1,
            options: [
              { id: "3m", labelTh: "3 เดือน", labelEn: "3 months" },
              { id: "6m", labelTh: "6 เดือน", labelEn: "6 months" },
              { id: "1y", labelTh: "1 ปี", labelEn: "1 year" },
              { id: "2y", labelTh: "2 ปี", labelEn: "2 years" },
            ] },
        ],
      },
      {
        id: "sl_sec2", titleTh: "งบประมาณและรายได้", titleEn: "Budget & revenue",
        fields: [
          { id: "monthlyRevenue", type: "text", labelTh: "รายได้ต่อเดือน (ประมาณการ)", labelEn: "Monthly revenue (est.)", required: true, span: 1, hint: "THB" },
          { id: "setupCost", type: "text", labelTh: "งบลงทุนตั้งต้น", labelEn: "Setup cost", span: 1, hint: "THB" },
          { id: "marginPct", type: "number", labelTh: "Margin %", labelEn: "Margin %", span: 1 },
          { id: "notes", type: "textarea", labelTh: "หมายเหตุเพิ่มเติม", labelEn: "Additional notes", span: 3 },
        ],
      },
    ],
  },
  {
    code: "FM-HR-02-01",
    icon: "users",
    color: "teal",
    category: "HR",
    titleTh: "ใบขอกำลังพล (Headcount Request)",
    titleEn: "Headcount Request",
    descTh: "ฝ่ายใดก็ใช้ได้ — ขอรับพนักงานเพิ่มสำหรับโครงการ/แผนก",
    descEn: "For any dept — request additional headcount",
    approvers: ["หัวหน้าฝ่ายผู้ขอ", "HR Manager", "ฝ่ายการเงิน"],
    avgDays: 2.5,
    sections: [
      {
        id: "hr_sec1", titleTh: "รายละเอียดความต้องการ", titleEn: "Request details",
        fields: [
          { id: "project", type: "text", labelTh: "โครงการ / แผนกปลายทาง", labelEn: "Project / target dept", required: true, span: 2 },
          { id: "headcount", type: "number", labelTh: "จำนวนกำลังพล", labelEn: "Headcount", required: true, span: 1 },
          { id: "startDate", type: "date", labelTh: "วันที่ต้องการเริ่มงาน", labelEn: "Desired start date", required: true, span: 1 },
          { id: "duration", type: "radio", labelTh: "ประเภทการจ้าง", labelEn: "Employment type", required: true, span: 2,
            options: [
              { id: "perm", labelTh: "ประจำ", labelEn: "Permanent" },
              { id: "contract", labelTh: "สัญญาจ้าง", labelEn: "Contract" },
              { id: "internship", labelTh: "ฝึกงาน", labelEn: "Internship" },
            ] },
        ],
      },
      {
        id: "hr_sec2", titleTh: "ตำแหน่งที่ต้องการ", titleEn: "Positions",
        fields: [
          { id: "positions", type: "textarea", labelTh: "ระบุตำแหน่งและจำนวน (แยกบรรทัด)", labelEn: "Positions and quantity (one per line)", required: true, span: 3, hint: "เช่น Call Center Agent x 26" },
          { id: "qualifications", type: "textarea", labelTh: "คุณสมบัติที่ต้องการ", labelEn: "Required qualifications", span: 3 },
          { id: "salaryRange", type: "text", labelTh: "ช่วงเงินเดือน (THB)", labelEn: "Salary range (THB)", span: 1 },
        ],
      },
    ],
  },
  {
    code: "FM-HR-02-03",
    icon: "user-plus",
    color: "teal",
    category: "HR",
    titleTh: "ขอเปิดข้อมูลพนักงานใหม่",
    titleEn: "New Employee Onboarding Request",
    descTh: "ตัวอย่างฟอร์มข้ามแผนก ออก Employee ID, ขอ Email จาก IT อัตโนมัติ",
    descEn: "Cross-dept template, generate Employee ID, auto-link IT email request",
    approvers: ["HR Manager", "หัวหน้าฝ่ายปลายทาง", "ฝ่าย IT"],
    avgDays: 2.5,
  },
  {
    code: "FM-FI-03-02",
    icon: "wallet",
    color: "emerald",
    category: "FI",
    titleTh: "ขอเบิกค่าใช้จ่ายโครงการ",
    titleEn: "Project Expense Reimbursement",
    descTh: "ตัวอย่างฟอร์มข้ามแผนก ขออนุมัติเบิกตามลำดับ Approver",
    descEn: "Cross-dept template, multi-level approval reimbursement",
    approvers: ["หัวหน้าโครงการ", "ผู้จัดการฝ่าย", "ฝ่ายบัญชี", "CFO"],
    avgDays: 3.5,
  },
];

export const USERS = {
  REQ001: { id: "REQ001", nameTh: "สมชาย ใจดี",          nameEn: "Somchai Jaidee",         titleTh: "Call Center Agent",                     titleEn: "Call Center Agent",                     dept: "Operations / Project AIS",  avatar: "SJ", color: "#3b82f6", username: "req001", password: "1234", role: "requester", isActive: true },
  REQ002: { id: "REQ002", nameTh: "ปิยะพร แสงทอง",       nameEn: "Piyaporn Saengthong",    titleTh: "Senior Agent",                           titleEn: "Senior Agent",                           dept: "Operations / Project TRUE", avatar: "PS", color: "#a855f7", username: "req002", password: "1234", role: "requester", isActive: true },
  REQ003: { id: "REQ003", nameTh: "ณัฐกานต์ วงศ์ใหญ่",  nameEn: "Natthakan Wongyai",      titleTh: "Team Leader",                            titleEn: "Team Leader",                            dept: "Operations / Project SCB",  avatar: "NW", color: "#f59e0b", username: "req003", password: "1234", role: "requester", isActive: true },
  APP001: { id: "APP001", nameTh: "ธนวัฒน์ ศรีสุวรรณ",  nameEn: "Tanawat Srisuwan",       titleTh: "Operations Manager",                     titleEn: "Operations Manager",                     dept: "Operations",                avatar: "TS", color: "#0ea5e9", username: "app001", password: "1234", role: "approver",  isActive: true },
  APP002: { id: "APP002", nameTh: "ชนิกานต์ พรหมศรี",   nameEn: "Chanikan Phromsri",      titleTh: "IT Manager",                             titleEn: "IT Manager",                             dept: "IT",                        avatar: "CP", color: "#10b981", username: "app002", password: "1234", role: "approver",  isActive: true },
  IT001:  { id: "IT001",  nameTh: "ปริญญา รักสะอาด",    nameEn: "Parinya Raksaard",       titleTh: "IT Support Engineer",                    titleEn: "IT Support Engineer",                    dept: "IT",                        avatar: "PR", color: "#06b6d4", username: "it001",  password: "1234", role: "it",        isActive: true },
  IT002:  { id: "IT002",  nameTh: "ภาสกร เลิศวิทย์",    nameEn: "Paskorn Lertwit",        titleTh: "Network & VoIP Engineer",                titleEn: "Network & VoIP Engineer",                dept: "IT",                        avatar: "PL", color: "#8b5cf6", username: "it002",  password: "1234", role: "it",        isActive: true },
  ADM001: { id: "ADM001", nameTh: "ศิริพร ทองคำ",        nameEn: "Siriporn Thongkam",      titleTh: "Quality Management Representative",       titleEn: "Quality Management Representative",       dept: "QMR Office",                avatar: "ST", color: "#ec4899", username: "adm001", password: "1234", role: "admin",     isActive: true },
  AUD001: { id: "AUD001", nameTh: "Mr. James Carter",    nameEn: "Mr. James Carter",       titleTh: "External Auditor",                       titleEn: "External Auditor",                       dept: "BSI Group",                 avatar: "JC", color: "#64748b", username: "aud001", password: "1234", role: "auditor",   isActive: true },
  SAL001: { id: "SAL001", nameTh: "อนุพงษ์ มั่งมี",     nameEn: "Anuphong Mangmee",       titleTh: "Senior Sales Executive",                 titleEn: "Senior Sales Executive",                 dept: "Sales",                     avatar: "AM", color: "#0284c7", username: "sal001", password: "1234", role: "requester", isActive: true },
  SAL002: { id: "SAL002", nameTh: "วรรณภา ใจกล้า",      nameEn: "Wannapha Jaikla",        titleTh: "Sales Director",                         titleEn: "Sales Director",                         dept: "Sales",                     avatar: "WJ", color: "#0369a1", username: "sal002", password: "1234", role: "approver",  isActive: true },
  HRM001: { id: "HRM001", nameTh: "พิชญา แสนสวัสดิ์",   nameEn: "Pitchaya Saensawat",     titleTh: "HR Manager",                             titleEn: "HR Manager",                             dept: "Human Resources",           avatar: "PS", color: "#0d9488", username: "hrm001", password: "1234", role: "approver",  isActive: true },
  HRM002: { id: "HRM002", nameTh: "ดวงใจ พิทักษ์",      nameEn: "Duangjai Pitak",         titleTh: "Recruitment Lead",                       titleEn: "Recruitment Lead",                       dept: "Human Resources",           avatar: "DP", color: "#14b8a6", username: "hrm002", password: "1234", role: "requester", isActive: true },
  FIN001: { id: "FIN001", nameTh: "อรพรรณ บุญรอด",      nameEn: "Orapan Boonrod",         titleTh: "Finance Manager",                        titleEn: "Finance Manager",                        dept: "Finance",                   avatar: "OB", color: "#059669", username: "fin001", password: "1234", role: "approver",  isActive: true },
};

// Job positions — admin-managed via User Management. Mutable for mock fallback.
export const POSITIONS = [
  { id: "POS001", nameTh: "General manager",                                          nameEn: "General manager",                          sortOrder: 1 },
  { id: "POS002", nameTh: "Managing Director",                                        nameEn: "Managing Director",                        sortOrder: 2 },
  { id: "POS003", nameTh: "Assistant Vice President",                                 nameEn: "Assistant Vice President",                 sortOrder: 3 },
  { id: "POS004", nameTh: "Call Center",                                              nameEn: "Call Center",                              sortOrder: 4 },
  { id: "POS005", nameTh: "Helpdesk Engineer",                                        nameEn: "Helpdesk Engineer",                        sortOrder: 5 },
  { id: "POS006", nameTh: "Manager",                                                  nameEn: "Manager",                                  sortOrder: 6 },
  { id: "POS007", nameTh: "Sr. Helpdesk Engineer",                                    nameEn: "Sr. Helpdesk Engineer",                    sortOrder: 7 },
  { id: "POS008", nameTh: "Senior HR Supervisor",                                     nameEn: "Senior HR Supervisor",                     sortOrder: 8 },
  { id: "POS009", nameTh: "Team Leader",                                              nameEn: "Team Leader",                              sortOrder: 9 },
  { id: "POS010", nameTh: "Senior Team Leader",                                       nameEn: "Senior Team Leader",                       sortOrder: 10 },
  { id: "POS011", nameTh: "Head Shift Helpdesk Engineer",                             nameEn: "Head Shift Helpdesk Engineer",             sortOrder: 11 },
  { id: "POS012", nameTh: "Quality Assurance",                                        nameEn: "Quality Assurance",                        sortOrder: 12 },
  { id: "POS013", nameTh: "Project Coordinator",                                      nameEn: "Project Coordinator",                      sortOrder: 13 },
  { id: "POS014", nameTh: "Helpdesk Trainee",                                         nameEn: "Helpdesk Trainee",                         sortOrder: 14 },
  { id: "POS015", nameTh: "Call Center Agent",                                        nameEn: "Call Center Agent",                        sortOrder: 15 },
  { id: "POS016", nameTh: "Sale Coordinator",                                         nameEn: "Sale Coordinator",                         sortOrder: 16 },
  { id: "POS017", nameTh: "Assistant Manager&PA",                                     nameEn: "Assistant Manager&PA",                     sortOrder: 17 },
  { id: "POS018", nameTh: "IT Support",                                               nameEn: "IT Support",                               sortOrder: 18 },
  { id: "POS019", nameTh: "Chauffeur",                                                nameEn: "Chauffeur",                                sortOrder: 19 },
  { id: "POS020", nameTh: "เจ้าหน้าที่ ฝ่ายทรัพยากรบุคคล และสื่อสารองค์กร",          nameEn: "เจ้าหน้าที่ ฝ่ายทรัพยากรบุคคล และสื่อสารองค์กร", sortOrder: 20 },
  { id: "POS021", nameTh: "IT Helpdesk",                                              nameEn: "IT Helpdesk",                              sortOrder: 21 },
  { id: "POS022", nameTh: "Engineer Support",                                         nameEn: "Engineer Support",                         sortOrder: 22 },
  { id: "POS023", nameTh: "Senior System Engineer",                                   nameEn: "Senior System Engineer",                   sortOrder: 23 },
];

// Per-menu access control. Mutable so Admin can edit via the UI.
// "ticketreport" is a locked-down role: it can ONLY see Service Ticket Summary.
export const ROLE_PERMISSIONS = {
  dashboard:    { requester: true,  approver: true,  it: true,  admin: true, auditor: true,  ticketreport: false },
  flows:        { requester: true,  approver: true,  it: true,  admin: true, auditor: true,  ticketreport: false },
  new:          { requester: true,  approver: true,  it: true,  admin: true, auditor: false, ticketreport: false },
  my:           { requester: true,  approver: true,  it: true,  admin: true, auditor: false, ticketreport: false },
  approvals:    { requester: false, approver: true,  it: false, admin: true, auditor: false, ticketreport: false },
  it:           { requester: false, approver: false, it: true,  admin: true, auditor: false, ticketreport: false },
  archive:      { requester: true,  approver: true,  it: true,  admin: true, auditor: true,  ticketreport: false },
  notif:        { requester: false, approver: false, it: true,  admin: true, auditor: false, ticketreport: false },
  caseSummary:  { requester: false, approver: false, it: true,  admin: true, auditor: true,  ticketreport: true  },
  settings:     { requester: false, approver: false, it: false, admin: true, auditor: false, ticketreport: false },
  integrations: { requester: false, approver: false, it: false, admin: true, auditor: false, ticketreport: false },
  users:        { requester: false, approver: false, it: false, admin: true, auditor: false, ticketreport: false },
};

export const REQUESTS = [
  {
    id: "SL0401-260515-0028",
    template: "FM-SL-04-01",
    titleTh: "เปิดโครงการใหม่ — AIS Premier Outbound Q3/2026",
    titleEn: "New Project — AIS Premier Outbound Q3/2026",
    requester: "SAL001",
    createdAt: "2026-05-15 09:30",
    updatedAt: "2026-05-18 16:20",
    priority: "high",
    status: "approved",
    currentStep: 3,
    steps: [
      { role: "Requester", user: "SAL001", action: "submitted", at: "2026-05-15 09:30", signed: true },
      { role: "Sales Manager", user: "SAL002", action: "approved", at: "2026-05-15 14:00", signed: true },
      { role: "Operations Director", user: "APP001", action: "approved", at: "2026-05-17 10:45", signed: true },
      { role: "CEO Office", user: "ADM001", action: "approved", at: "2026-05-18 16:20", signed: true },
    ],
    payload: {
      projectName: "AIS Premier Outbound Q3/2026",
      client: "AIS (Advanced Info Service)",
      seatCount: 30,
      goLive: "2026-07-01",
      monthlyRevenue: "THB 3,200,000",
    },
    links: { triggers: ["HR0201-260518-0042", "IT0110-260518-0145"] },
  },
  {
    id: "HR0201-260518-0042",
    template: "FM-HR-02-01",
    titleTh: "ขอกำลังพล 30 คน สำหรับโครงการ AIS Premier",
    titleEn: "Headcount Request — 30 agents for AIS Premier",
    requester: "REQ003",
    createdAt: "2026-05-18 16:25",
    updatedAt: "2026-05-22 11:00",
    priority: "high",
    status: "approved",
    currentStep: 3,
    autoSpawned: true,
    steps: [
      { role: "Requester", user: "REQ003", action: "submitted", at: "2026-05-18 16:25", signed: true, auto: true },
      { role: "หัวหน้าฝ่ายผู้ขอ", user: "APP001", action: "approved", at: "2026-05-19 09:15", signed: true },
      { role: "HR Manager", user: "HRM001", action: "approved", at: "2026-05-20 14:30", signed: true },
      { role: "ฝ่ายการเงิน", user: "FIN001", action: "approved", at: "2026-05-22 11:00", signed: true },
    ],
    payload: {
      headcount: 30,
      positions: ["Call Center Agent x 26", "Team Leader x 3", "QA x 1"],
      startDate: "2026-06-15",
      project: "AIS Premier Outbound Q3/2026",
    },
    links: {
      triggeredBy: "SL0401-260515-0028",
      triggers: ["IT0101-260523-0149", "IT0101-260524-0150", "IT0101-260524-0151"],
    },
  },
  {
    id: "IT0110-260518-0145",
    template: "FM-IT-01-10",
    titleTh: "ติดตั้งจุดทำงาน 30 ที่ — โครงการ AIS Premier ชั้น 7",
    titleEn: "Install 30 stations — Project AIS Premier floor 7",
    requester: "IT002",
    createdAt: "2026-05-18 16:25",
    updatedAt: "2026-05-23 09:30",
    priority: "high",
    status: "inProgress",
    currentStep: 3,
    autoSpawned: true,
    steps: [
      { role: "Requester", user: "IT002", action: "submitted", at: "2026-05-18 16:25", signed: true, auto: true },
      { role: "หัวหน้าโปรเจกต์", user: "APP001", action: "approved", at: "2026-05-19 11:00", signed: true },
      { role: "ผู้จัดการ IT", user: "APP002", action: "approved", at: "2026-05-20 15:00", signed: true },
      { role: "เจ้าหน้าที่ IT", user: "IT002", action: "in_progress", at: "2026-05-23 09:30", signed: false },
    ],
    payload: {
      stations: 30,
      includes: ["PC Desktop", "Headset", "IP Phone", "Softphone License"],
      goLive: "2026-06-30",
    },
    links: { triggeredBy: "SL0401-260515-0028" },
  },
  {
    id: "IT0101-260523-0149",
    template: "FM-IT-01-01",
    titleTh: "เปิดสิทธิ์ใช้ระบบ — กชกร ผ่องใส (รุ่นแรก)",
    titleEn: "System access — Kotchakorn Phongsai (cohort 1)",
    requester: "HRM002",
    createdAt: "2026-05-23 10:00",
    updatedAt: "2026-05-24 14:15",
    priority: "normal",
    status: "approved",
    currentStep: 3,
    autoSpawned: true,
    steps: [
      { role: "Requester", user: "HRM002", action: "submitted", at: "2026-05-23 10:00", signed: true, auto: true },
      { role: "หัวหน้าฝ่าย", user: "APP001", action: "approved", at: "2026-05-23 16:30", signed: true },
      { role: "ผู้จัดการ IT", user: "APP002", action: "approved", at: "2026-05-24 09:45", signed: true },
      { role: "เจ้าหน้าที่ IT", user: "IT001", action: "in_progress", at: "2026-05-24 14:15", signed: false },
    ],
    payload: {
      employeeName: "กชกร ผ่องใส",
      employeeId: "EMP-2526-018",
      position: "Call Center Agent",
      department: "Operations / AIS Premier",
      effectiveDate: "2026-06-15",
      employeeType: "ประจำ",
      requestType: "ใช้งาน",
      items: ["Email บริษัท (User, 10 GB, ปฏิทิน)", "PBX Extension (User)", "Headset Personal", "License MS Office", "บัตรพนักงาน + สายคล้อง"],
      purpose: "พนักงานใหม่จากการอนุมัติกำลังพล HR0201-260518-0042 เริ่มงาน 15 มิ.ย. 2569",
    },
    links: { triggeredBy: "HR0201-260518-0042" },
  },
  {
    id: "IT0101-260524-0142",
    template: "FM-IT-01-01",
    titleTh: "ขอเปิด Email และสิทธิ์ PBX สำหรับพนักงานใหม่",
    titleEn: "New email + PBX access for new hire",
    requester: "REQ003",
    createdAt: "2026-05-24 09:14",
    updatedAt: "2026-05-25 11:02",
    priority: "normal",
    status: "pending",
    currentStep: 2,
    steps: [
      { role: "Requester", user: "REQ003", action: "submitted", at: "2026-05-24 09:14", signed: true },
      { role: "หัวหน้าฝ่าย", user: "APP001", action: "approved", at: "2026-05-24 14:32", signed: true },
      { role: "ผู้จัดการ IT", user: "APP002", action: "pending", at: null, signed: false },
      { role: "เจ้าหน้าที่ IT", user: "IT001", action: "queued", at: null, signed: false },
    ],
    payload: {
      employeeName: "นพดล ศรีจันทร์",
      employeeId: "EMP-2526-014",
      position: "Call Center Agent",
      department: "Operations / Project AIS",
      effectiveDate: "2026-06-01",
      employeeType: "ประจำ",
      requestType: "ใช้งาน",
      items: ["Email บริษัท (User, 10 GB, ปฏิทิน)", "PBX Extension (User)", "Headset Personal", "License MS Office", "บัตรพนักงาน + สายคล้อง"],
      purpose: "พนักงานใหม่เข้ารับตำแหน่ง 1 มิ.ย. 2569 ต้องการอุปกรณ์และสิทธิ์ใช้งานครบเพื่อเริ่มงาน",
    },
  },
  {
    id: "IT0109-260525-0143",
    template: "FM-IT-01-09",
    titleTh: "สร้างคิวใหม่ Project SCB-Premier",
    titleEn: "New PBX queue for Project SCB-Premier",
    requester: "REQ003",
    createdAt: "2026-05-25 08:42",
    updatedAt: "2026-05-25 08:42",
    priority: "high",
    status: "pending",
    currentStep: 1,
    steps: [
      { role: "Requester", user: "REQ003", action: "submitted", at: "2026-05-25 08:42", signed: true },
      { role: "หัวหน้าโปรเจกต์", user: "APP001", action: "pending", at: null, signed: false },
      { role: "ผู้จัดการ IT", user: "APP002", action: "queued", at: null, signed: false },
      { role: "เจ้าหน้าที่ IT", user: "IT002", action: "queued", at: null, signed: false },
    ],
    payload: {
      queueName: "SCB-Premier-Inbound",
      ringStrategy: "Round Robin",
      outbound: ["Domestic"],
      members: 12,
      goLive: "2026-06-03 09:00",
    },
  },
  {
    id: "IT0111-260525-0144",
    template: "FM-IT-01-11",
    titleTh: "หูฟัง Jabra Evolve 30 ไม่มีเสียง — ด่วนมาก",
    titleEn: "Jabra Evolve 30 headset no audio — urgent",
    requester: "REQ001",
    createdAt: "2026-05-25 10:18",
    updatedAt: "2026-05-25 10:51",
    priority: "urgent",
    status: "inProgress",
    currentStep: 1,
    steps: [
      { role: "Requester", user: "REQ001", action: "submitted", at: "2026-05-25 10:18", signed: true },
      { role: "เจ้าหน้าที่ IT", user: "IT001", action: "in_progress", at: "2026-05-25 10:51", signed: false },
    ],
    payload: {
      assetId: "TTM-HS-0431",
      severity: "เร่งด่วนมาก (Impact 100%)",
      symptoms: "หูฟังไม่มีเสียงทั้งซ้ายและขวา ทดสอบเสียบเครื่องอื่นก็ไม่ได้ยิน",
      ticketNo: "TKT-0598",
    },
  },
  {
    id: "IT0110-260523-0140",
    template: "FM-IT-01-10",
    titleTh: "ขยายจุดติดตั้ง 8 ที่นั่ง Project TRUE ชั้น 5",
    titleEn: "Expand 8 stations, Project TRUE floor 5",
    requester: "REQ002",
    createdAt: "2026-05-23 15:02",
    updatedAt: "2026-05-25 09:30",
    priority: "normal",
    status: "approved",
    currentStep: 3,
    steps: [
      { role: "Requester", user: "REQ002", action: "submitted", at: "2026-05-23 15:02", signed: true },
      { role: "หัวหน้าโปรเจกต์", user: "APP001", action: "approved", at: "2026-05-23 17:11", signed: true },
      { role: "ผู้จัดการ IT", user: "APP002", action: "approved", at: "2026-05-24 09:45", signed: true },
      { role: "เจ้าหน้าที่ IT", user: "IT002", action: "in_progress", at: "2026-05-25 09:30", signed: false },
    ],
    payload: {
      stations: 8,
      includes: ["PC Desktop", "Headset", "IP Phone"],
      goLive: "2026-06-10",
    },
  },
  {
    id: "IT0101-260522-0138",
    template: "FM-IT-01-01",
    titleTh: "ขอ VPN Account สำหรับ Work from home",
    titleEn: "VPN account for work from home",
    requester: "REQ002",
    createdAt: "2026-05-22 11:30",
    updatedAt: "2026-05-23 10:14",
    priority: "normal",
    status: "done",
    currentStep: 4,
    steps: [
      { role: "Requester", user: "REQ002", action: "submitted", at: "2026-05-22 11:30", signed: true },
      { role: "หัวหน้าฝ่าย", user: "APP001", action: "approved", at: "2026-05-22 14:00", signed: true },
      { role: "ผู้จัดการ IT", user: "APP002", action: "approved", at: "2026-05-23 09:00", signed: true },
      { role: "เจ้าหน้าที่ IT", user: "IT002", action: "done", at: "2026-05-23 10:14", signed: true },
    ],
    payload: { items: ["VPN Account"], purpose: "ทำงานจากบ้านวันศุกร์" },
    output: {
      deliveredAt: "2026-05-23 10:14",
      deliveredBy: "IT002",
      items: [
        { label: "VPN Account", value: "somsak.j@ttm.co.th" },
        { label: "รหัสผ่านชั่วคราว", value: "VPN@Temp#2026" },
        { label: "Server / Gateway", value: "vpn.ttm.co.th:1194" },
      ],
      note: "ติดตั้ง FortiClient แล้ว ให้เปลี่ยนรหัสผ่านทันทีหลังเข้าใช้งานครั้งแรก",
    },
  },
  {
    id: "IT0111-260521-0136",
    template: "FM-IT-01-11",
    titleTh: "ลืมรหัสผ่าน Email",
    titleEn: "Forgot email password",
    requester: "REQ001",
    createdAt: "2026-05-21 08:05",
    updatedAt: "2026-05-21 08:42",
    priority: "normal",
    status: "done",
    currentStep: 2,
    steps: [
      { role: "Requester", user: "REQ001", action: "submitted", at: "2026-05-21 08:05", signed: true },
      { role: "เจ้าหน้าที่ IT", user: "IT001", action: "done", at: "2026-05-21 08:42", signed: true },
    ],
    payload: {},
  },
  {
    id: "HR0203-260520-0089",
    template: "FM-HR-02-03",
    titleTh: "เปิดข้อมูลพนักงานใหม่ — กชกร ผ่องใส",
    titleEn: "New employee onboarding — Kotchakorn Phongsai",
    requester: "REQ003",
    createdAt: "2026-05-20 09:00",
    updatedAt: "2026-05-22 16:10",
    priority: "normal",
    status: "approved",
    currentStep: 3,
    steps: [
      { role: "Requester", user: "REQ003", action: "submitted", at: "2026-05-20 09:00", signed: true },
      { role: "HR Manager", user: "APP001", action: "approved", at: "2026-05-20 13:15", signed: true },
      { role: "หัวหน้าฝ่าย", user: "APP002", action: "approved", at: "2026-05-21 09:30", signed: true },
      { role: "ฝ่าย IT", user: "IT001", action: "in_progress", at: "2026-05-22 16:10", signed: false },
    ],
    payload: {},
  },
  {
    id: "IT0109-260518-0131",
    template: "FM-IT-01-09",
    titleTh: "ย้าย Agent 5 คน จาก Queue AIS-A ไป AIS-B",
    titleEn: "Transfer 5 agents from AIS-A to AIS-B",
    requester: "REQ001",
    createdAt: "2026-05-18 10:00",
    updatedAt: "2026-05-19 11:20",
    priority: "normal",
    status: "rejected",
    currentStep: 1,
    rejectReason: "ต้องได้รับการยืนยันจาก Project Manager AIS-B ก่อน",
    steps: [
      { role: "Requester", user: "REQ001", action: "submitted", at: "2026-05-18 10:00", signed: true },
      { role: "หัวหน้าโปรเจกต์", user: "APP001", action: "rejected", at: "2026-05-19 11:20", signed: true },
    ],
    payload: {},
  },
];

export const NOTIFICATIONS = [
  { id: "N-0421", channel: "line", to: "Group: IT Operations", subject: "📋 คำขอใหม่ IT0109-260525-0143 — สร้างคิว SCB-Premier", at: "2026-05-25 08:42", status: "delivered", reqId: "IT0109-260525-0143" },
  { id: "N-0420", channel: "email", to: "it-team@talktome.co.th", subject: "[Approve Required] IT0109-260525-0143", at: "2026-05-25 08:42", status: "delivered", reqId: "IT0109-260525-0143" },
  { id: "N-0419", channel: "inapp", to: "APP001", subject: "มีคำขอใหม่รออนุมัติ (1 รายการ)", at: "2026-05-25 08:42", status: "read", reqId: "IT0109-260525-0143" },
  { id: "N-0418", channel: "line", to: "Group: IT Support", subject: "🚨 แจ้งซ่อมด่วนมาก — หูฟัง TTM-HS-0431", at: "2026-05-25 10:18", status: "delivered", reqId: "IT0111-260525-0144" },
  { id: "N-0417", channel: "email", to: "parinya.r@talktome.co.th", subject: "[Ticket TKT-0598] Headset no audio — urgent", at: "2026-05-25 10:18", status: "delivered", reqId: "IT0111-260525-0144" },
  { id: "N-0416", channel: "line", to: "REQ001 (สมชาย)", subject: "✅ คำขอ TKT-0598 ถูกรับเข้าคิวงานแล้ว — IT001 รับงาน", at: "2026-05-25 10:51", status: "delivered", reqId: "IT0111-260525-0144" },
  { id: "N-0415", channel: "email", to: "tanawat.s@talktome.co.th", subject: "[Approve Required] IT0101-260524-0142", at: "2026-05-24 09:14", status: "delivered", reqId: "IT0101-260524-0142" },
  { id: "N-0414", channel: "line", to: "APP001 (ธนวัฒน์)", subject: "📋 รออนุมัติคำขอเปิด Email พนักงานใหม่", at: "2026-05-24 09:14", status: "delivered", reqId: "IT0101-260524-0142" },
  { id: "N-0413", channel: "email", to: "chanikan.p@talktome.co.th", subject: "[Approve Required] IT0101-260524-0142 (ขั้นที่ 2)", at: "2026-05-24 14:32", status: "delivered", reqId: "IT0101-260524-0142" },
  { id: "N-0412", channel: "line", to: "REQ003 (ณัฐกานต์)", subject: "✅ ขั้นที่ 1/3 อนุมัติแล้วโดย ธนวัฒน์ ศ.", at: "2026-05-24 14:32", status: "delivered", reqId: "IT0101-260524-0142" },
];

export const FLOW_TEMPLATES = [
  {
    id: "FT-NEW-PROJECT",
    titleTh: "เปิดโครงการใหม่",
    titleEn: "New Project Setup",
    descTh: "ตั้งแต่ฝ่ายขายเปิดโครงการ → HR เปิดอัตรากำลัง → IT เตรียมอุปกรณ์ + เปิดสิทธิ์พนักงาน",
    descEn: "End-to-end: Sales kickoff → HR headcount → IT setup → User access",
    icon: "trending-up",
    color: "blue",
    owner: "Sales",
    avgDays: 14,
    steps: [
      { id: "s1", form: "FM-SL-04-01", deptTh: "ฝ่ายขาย", deptEn: "Sales", optional: false },
      { id: "s2", form: "FM-HR-02-01", deptTh: "ฝ่ายบุคคล", deptEn: "HR", optional: false, dependsOn: "s1" },
      { id: "s3", form: "FM-IT-01-10", deptTh: "ฝ่ายไอที", deptEn: "IT", optional: false, dependsOn: "s1", parallelWith: "s2" },
      { id: "s4", form: "FM-IT-01-01", deptTh: "ฝ่ายไอที", deptEn: "IT", optional: false, dependsOn: "s2", multiplePerHeadcount: true },
      { id: "s5", form: "FM-IT-01-09", deptTh: "ฝ่ายไอที", deptEn: "IT", optional: true, dependsOn: "s3" },
    ],
  },
  {
    id: "FT-NEW-EMPLOYEE",
    titleTh: "รับพนักงานใหม่",
    titleEn: "New Employee Onboarding",
    descTh: "HR เปิดข้อมูลพนักงาน → IT เปิดสิทธิ์ + อุปกรณ์",
    descEn: "HR opens employee record → IT issues access + equipment",
    icon: "user-plus",
    color: "teal",
    owner: "HR",
    avgDays: 5,
    steps: [
      { id: "s1", form: "FM-HR-02-03", deptTh: "ฝ่ายบุคคล", deptEn: "HR", optional: false },
      { id: "s2", form: "FM-IT-01-01", deptTh: "ฝ่ายไอที", deptEn: "IT", optional: false, dependsOn: "s1" },
    ],
  },
  {
    id: "FT-CLOSE-PROJECT",
    titleTh: "ปิดโครงการ / ส่งคืนทรัพย์สิน",
    titleEn: "Project Closure & Asset Return",
    descTh: "ฝ่ายขายแจ้งปิด → HR เลิกจ้าง → IT คืนสิทธิ์ + เก็บอุปกรณ์ → การเงินทำรอบปิดสุดท้าย",
    descEn: "Sales notice → HR offboarding → IT revoke access + collect → Finance final billing",
    icon: "archive",
    color: "rose",
    owner: "Sales",
    avgDays: 10,
    steps: [
      { id: "s1", form: "FM-SL-04-01", deptTh: "ฝ่ายขาย", deptEn: "Sales", optional: false, labelTh: "แจ้งปิดโครงการ", labelEn: "Closure notice" },
      { id: "s2", form: "FM-IT-01-01", deptTh: "ฝ่ายไอที", deptEn: "IT", optional: false, dependsOn: "s1", labelTh: "ยกเลิกสิทธิ์พนักงาน", labelEn: "Revoke user access" },
      { id: "s3", form: "FM-IT-01-10", deptTh: "ฝ่ายไอที", deptEn: "IT", optional: false, dependsOn: "s2", labelTh: "เก็บอุปกรณ์", labelEn: "Collect equipment" },
      { id: "s4", form: "FM-FI-03-02", deptTh: "ฝ่ายการเงิน", deptEn: "Finance", optional: false, dependsOn: "s3", labelTh: "ปิดงบโครงการ", labelEn: "Final billing" },
    ],
  },
];

export const FLOW_INSTANCES = [
  {
    id: "FL-260515-001",
    template: "FT-NEW-PROJECT",
    titleTh: "AIS Premier Outbound Q3/2026",
    titleEn: "AIS Premier Outbound Q3/2026",
    requester: "SAL001",
    createdAt: "2026-05-15 09:30",
    updatedAt: "2026-05-25 09:30",
    status: "active",
    currentStepIdx: 2,
    stepStates: [
      { stepId: "s1", reqIds: ["SL0401-260515-0028"], status: "approved", completedAt: "2026-05-18 16:20" },
      { stepId: "s2", reqIds: ["HR0201-260518-0042"], status: "approved", completedAt: "2026-05-22 11:00" },
      { stepId: "s3", reqIds: ["IT0110-260518-0145"], status: "inProgress" },
      { stepId: "s4", reqIds: ["IT0101-260523-0149"], status: "inProgress" },
      { stepId: "s5", reqIds: [], status: "pending" },
    ],
  },
  {
    id: "FL-260522-002",
    template: "FT-NEW-EMPLOYEE",
    titleTh: "Onboarding กชกร ผ่องใส",
    titleEn: "Onboarding — Kotchakorn Phongsai",
    requester: "HRM001",
    createdAt: "2026-05-20 09:00",
    updatedAt: "2026-05-24 14:15",
    status: "active",
    currentStepIdx: 1,
    stepStates: [
      { stepId: "s1", reqIds: ["HR0203-260520-0089"], status: "approved", completedAt: "2026-05-22 16:10" },
      { stepId: "s2", reqIds: [], status: "inProgress" },
    ],
  },
  {
    id: "FL-260510-003",
    template: "FT-NEW-PROJECT",
    titleTh: "TRUE Mobile Care Outbound",
    titleEn: "TRUE Mobile Care Outbound",
    requester: "SAL002",
    createdAt: "2026-04-22 10:00",
    updatedAt: "2026-05-08 16:00",
    status: "done",
    currentStepIdx: 4,
    stepStates: [
      { stepId: "s1", reqIds: ["SL0401-260422-0019"], status: "approved", completedAt: "2026-04-24 11:00" },
      { stepId: "s2", reqIds: ["HR0201-260425-0028"], status: "approved", completedAt: "2026-04-28 09:00" },
      { stepId: "s3", reqIds: ["IT0110-260425-0098"], status: "approved", completedAt: "2026-04-30 16:00" },
      { stepId: "s4", reqIds: ["IT0101-260502-0112", "IT0101-260502-0113"], status: "done", completedAt: "2026-05-05 14:00" },
      { stepId: "s5", reqIds: ["IT0109-260506-0102"], status: "done", completedAt: "2026-05-08 16:00" },
    ],
  },
];

// FM-IT-01-01 -> IT0101 ; FM-HR-02-03 -> HR0203 ; FM-FI-03-02 -> FI0302
export function shortFormCode(code) {
  return String(code || "").replace(/^FM-/, "").replace(/-/g, "");
}

/* ─────────────────────────────────────────────────────────────
   Time helpers — everything in the app is displayed in
   Asia/Bangkok (UTC+7). DB columns are TIMESTAMPTZ (UTC) but
   user-facing strings ALWAYS go through these helpers so:
     - timestamps generated client-side (step "at", submit time)
     - timestamps shown from the DB
   stay consistent regardless of where the code runs
   (browser local TZ, Vercel UTC server, etc.).
   ───────────────────────────────────────────────────────────── */
const _BKK_FMT = (typeof Intl !== "undefined" && Intl.DateTimeFormat)
  ? new Intl.DateTimeFormat("en-CA", {
      timeZone: "Asia/Bangkok",
      year: "numeric", month: "2-digit", day: "2-digit",
      hour: "2-digit", minute: "2-digit", hour12: false,
    })
  : null;

/** "YYYY-MM-DD HH:MM" in Asia/Bangkok. Accepts a Date, ISO string, or
 *  any value Date() accepts. Returns "" on bad input. */
export function fmtBKK(d = new Date()) {
  if (typeof d === "string") d = new Date(d);
  if (!(d instanceof Date) || isNaN(d.getTime())) return "";
  if (_BKK_FMT) {
    const parts = _BKK_FMT.formatToParts(d);
    const get = (t) => parts.find(p => p.type === t)?.value || "";
    return `${get("year")}-${get("month")}-${get("day")} ${get("hour")}:${get("minute")}`;
  }
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

/** "YYYY-MM-DD" in Asia/Bangkok. */
export function todayBKK(d = new Date()) {
  return fmtBKK(d).slice(0, 10);
}
